application: socialcanvas
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
  
- url: /dojo/.*
  script: $PYTHON_LIB/google/appengine/ext/zipserve

- url: /dijit/.*
  script: $PYTHON_LIB/google/appengine/ext/zipserve

- url: /dojox/.*
  script: $PYTHON_LIB/google/appengine/ext/zipserve

# Static: JS files
- url: /js
  static_dir: js   
  
- url: /test.*
  script: gaeunit.py
  
- url: /images
  static_dir: images
  
- url: /favicon.ico
  static_files: /favicon.ico
  upload: /favicon.ico

- url: /.*
  script: src/main.py
  

  
